# Generated by Django 4.0 on 2022-08-11 11:14

import api.models
import api.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField(max_length=200)),
                ('driver_license', models.CharField(max_length=20)),
                ('driver_license_state', models.CharField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming')], max_length=25)),
                ('ssn', models.IntegerField(blank=True, null=True)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('pets', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('number_of_pets', models.IntegerField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_num', models.IntegerField()),
                ('property_road', models.CharField(max_length=200)),
                ('rent', models.IntegerField(default=1000)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming')], max_length=25)),
                ('zip', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField(max_length=3)),
                ('sq_foot', models.IntegerField()),
                ('property_title', models.CharField(blank=True, max_length=200, null=True)),
                ('property_short_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='property short description')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=api.models.upload_picture)),
                ('thumbnail_alt_text', models.CharField(default='Property image.', max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('available_date', models.DateField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteStaticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=200, upload_to='static/images/website_static_images')),
                ('image_alt_text', models.CharField(default='image alt text', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_additional_picture)),
                ('alt_text', models.CharField(max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='PersonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=api.models.rename_upload, validators=[api.validators.validate_file_extension])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=200)),
                ('employer_address', models.CharField(max_length=200)),
                ('employer_city', models.CharField(max_length=200)),
                ('employer_state', models.CharField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming')], max_length=25)),
                ('employer_zip', models.IntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('job_start_date', models.DateField()),
                ('supervisor_name', models.CharField(max_length=200)),
                ('gross_income', models.BigIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_move_in_date', models.DateField(max_length=10, null=True)),
                ('application_date', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_start_date', models.DateField(blank=True, max_length=10, null=True)),
                ('address_end_date', models.DateField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming')], max_length=15, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('landlord', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_phone', models.BigIntegerField(blank=True, null=True)),
                ('reason_for_moving', models.TextField(blank=True, max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'unique_together': {('person', 'application')},
            },
        ),
    ]
