# Generated by Django 4.0 on 2022-08-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
